/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    'class-templates': ClassTemplate;
    instructors: Instructor;
    'class-sessions': ClassSession;
    memberships: Membership;
    'membership-schedules': MembershipSchedule;
    bookings: Booking;
    subscriptions: Subscription;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'class-templates': ClassTemplatesSelect<false> | ClassTemplatesSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    'class-sessions': ClassSessionsSelect<false> | ClassSessionsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'membership-schedules': MembershipSchedulesSelect<false> | MembershipSchedulesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * First name
   */
  firstName?: string | null;
  /**
   * Last name
   */
  lastName?: string | null;
  /**
   * Phone number
   */
  phone?: string | null;
  /**
   * Street address
   */
  address?: string | null;
  city?: string | null;
  postalCode?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Tag name (e.g., "Kids & Family", "Wine", "Ceramics")
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional color code for tag display (e.g., "#FF5733")
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-templates".
 */
export interface ClassTemplate {
  id: number;
  title: string;
  slug: string;
  /**
   * One-time: Single event. Recurring: Repeating schedule. Membership Template: Part of a subscription membership.
   */
  classType: 'one-time' | 'recurring' | 'membership-template';
  description?: string | null;
  /**
   * Assigned instructor for this class
   */
  instructor?: (number | null) | Instructor;
  /**
   * Main image for the class
   */
  featuredImage?: (number | null) | Media;
  /**
   * Additional images for class detail carousel
   */
  gallery?: (number | Media)[] | null;
  /**
   * Price per person in cents (e.g., 4500 = €45.00). Total booking price = priceCents × numberOfPeople
   */
  priceCents: number;
  currency?: string | null;
  /**
   * Duration of the class in minutes
   */
  durationMinutes: number;
  /**
   * Maximum number of participants per session
   */
  maxCapacity: number;
  /**
   * Class location or venue
   */
  location?: string | null;
  /**
   * Tags for filtering (e.g., Kids & Family, Wine, Ceramics)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Define recurring schedules for this class (e.g., "Every Thursday at 18:00")
   */
  recurrencePatterns?:
    | {
        frequency: 'weekly' | 'biweekly' | 'monthly';
        /**
         * Days of the week this class occurs
         */
        daysOfWeek: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[];
        /**
         * Start time in HH:MM format (e.g., "18:00")
         */
        startTime: string;
        /**
         * Date when the recurrence starts
         */
        startDate: string;
        /**
         * Date when the recurrence ends (leave empty for indefinite)
         */
        endDate?: string | null;
        /**
         * Timezone for the recurring schedule
         */
        timezone: string;
        /**
         * Whether this recurrence pattern is currently active
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Instructor biography
   */
  bio?: string | null;
  /**
   * Instructor profile photo
   */
  photo?: (number | null) | Media;
  email: string;
  phone?: string | null;
  /**
   * Teaching specialties (e.g., "Watercolor, Acrylics, Portrait")
   */
  specialties?: string | null;
  /**
   * Whether this instructor is currently available
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-sessions".
 */
export interface ClassSession {
  id: number;
  /**
   * The class template this session belongs to
   */
  classTemplate: number | ClassTemplate;
  /**
   * Start date and time (stored in UTC)
   */
  startDateTime: string;
  /**
   * End date and time (stored in UTC)
   */
  endDateTime: string;
  /**
   * Timezone for display purposes (e.g., "Europe/Madrid")
   */
  timezone?: string | null;
  status: 'scheduled' | 'cancelled' | 'completed';
  /**
   * Current available spots (auto-calculated based on bookings). Leave empty to inherit from class template maxCapacity.
   */
  availableSpots?: number | null;
  /**
   * Internal notes about this specific session
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  title: string;
  slug: string;
  /**
   * Membership description and benefits
   */
  description?: string | null;
  /**
   * Class templates included in this membership
   */
  classTemplates?: (number | ClassTemplate)[] | null;
  /**
   * Main image for the membership
   */
  featuredImage?: (number | null) | Media;
  /**
   * Monthly subscription price in cents (e.g., 12000 = €120.00)
   */
  monthlyPriceCents: number;
  currency?: string | null;
  billingCycle: 'monthly' | 'quarterly' | 'annual';
  /**
   * Maximum number of active subscriptions
   */
  maxEnrollments: number;
  /**
   * Tags for filtering (e.g., Kids & Family, Wine, Ceramics)
   */
  tags?: (number | Tag)[] | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links memberships to specific class sessions available during a period
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-schedules".
 */
export interface MembershipSchedule {
  id: number;
  /**
   * The membership this schedule belongs to
   */
  membership: number | Membership;
  /**
   * Class sessions that are available to membership subscribers
   */
  classSessions: (number | ClassSession)[];
  /**
   * When this schedule period starts
   */
  startDate: string;
  /**
   * When this schedule period ends
   */
  endDate: string;
  /**
   * Whether this schedule is currently active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * User who made the booking (optional for guest bookings)
   */
  user?: (number | null) | User;
  /**
   * First name of the person booking
   */
  firstName: string;
  /**
   * Last name of the person booking
   */
  lastName: string;
  /**
   * Email address for booking confirmation
   */
  email: string;
  /**
   * Phone number for contact
   */
  phone: string;
  /**
   * The specific class session being booked
   */
  classSession: number | ClassSession;
  /**
   * Number of spots booked
   */
  numberOfPeople: number;
  status: 'pending' | 'confirmed' | 'cancelled' | 'attended' | 'no-show';
  paymentStatus: 'unpaid' | 'paid' | 'refunded' | 'failed';
  /**
   * Stripe Payment Intent ID
   */
  stripePaymentIntentId?: string | null;
  bookingDate: string;
  /**
   * Whether the user has checked in for the class
   */
  checkedIn?: boolean | null;
  /**
   * Internal notes or special requests
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * Subscribed user
   */
  user: number | User;
  /**
   * The membership the user is subscribed to
   */
  membership: number | Membership;
  enrollmentDate: string;
  status: 'active' | 'paused' | 'cancelled' | 'expired';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Stripe Subscription ID
   */
  stripeSubscriptionId?: string | null;
  /**
   * Next billing date for subscription
   */
  nextBillingDate?: string | null;
  /**
   * Date when subscription was cancelled
   */
  cancellationDate?: string | null;
  /**
   * Internal notes about this subscription
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'class-templates';
        value: number | ClassTemplate;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'class-sessions';
        value: number | ClassSession;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'membership-schedules';
        value: number | MembershipSchedule;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  address?: T;
  city?: T;
  postalCode?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-templates_select".
 */
export interface ClassTemplatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  classType?: T;
  description?: T;
  instructor?: T;
  featuredImage?: T;
  gallery?: T;
  priceCents?: T;
  currency?: T;
  durationMinutes?: T;
  maxCapacity?: T;
  location?: T;
  tags?: T;
  recurrencePatterns?:
    | T
    | {
        frequency?: T;
        daysOfWeek?: T;
        startTime?: T;
        startDate?: T;
        endDate?: T;
        timezone?: T;
        isActive?: T;
        id?: T;
      };
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  photo?: T;
  email?: T;
  phone?: T;
  specialties?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-sessions_select".
 */
export interface ClassSessionsSelect<T extends boolean = true> {
  classTemplate?: T;
  startDateTime?: T;
  endDateTime?: T;
  timezone?: T;
  status?: T;
  availableSpots?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  classTemplates?: T;
  featuredImage?: T;
  monthlyPriceCents?: T;
  currency?: T;
  billingCycle?: T;
  maxEnrollments?: T;
  tags?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-schedules_select".
 */
export interface MembershipSchedulesSelect<T extends boolean = true> {
  membership?: T;
  classSessions?: T;
  startDate?: T;
  endDate?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  classSession?: T;
  numberOfPeople?: T;
  status?: T;
  paymentStatus?: T;
  stripePaymentIntentId?: T;
  bookingDate?: T;
  checkedIn?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  membership?: T;
  enrollmentDate?: T;
  status?: T;
  paymentStatus?: T;
  stripeSubscriptionId?: T;
  nextBillingDate?: T;
  cancellationDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}