/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    classes: Class;
    courses: Course;
    instructors: Instructor;
    sessions: Session;
    bookings: Booking;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    classes: {
      sessions: 'sessions';
    };
    courses: {
      sessions: 'sessions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * First name
   */
  firstName?: string | null;
  /**
   * Last name
   */
  lastName?: string | null;
  /**
   * Phone number
   */
  phone?: string | null;
  /**
   * Street address
   */
  address?: string | null;
  city?: string | null;
  postalCode?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Tag name (e.g., "Kids & Family", "Wine", "Ceramics")
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional color code for tag display (e.g., "#FF5733")
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  title: string;
  slug: string;
  /**
   * One-time: Create sessions manually. Recurring: Auto-generate sessions from schedule.
   */
  classType: 'one-time' | 'recurring';
  description?: string | null;
  instructor?: (number | null) | Instructor;
  featuredImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Price per person in cents (e.g., 4500 = €45.00)
   */
  priceCents: number;
  currency?: ('eur' | 'usd') | null;
  /**
   * Duration of the class in minutes
   */
  durationMinutes: number;
  /**
   * Maximum participants per session
   */
  maxCapacity: number;
  location?: string | null;
  tags?: (number | Tag)[] | null;
  isPublished?: boolean | null;
  /**
   * Configure automatic session generation for recurring classes.
   */
  schedule?: {
    /**
     * First session date
     */
    startDate?: string | null;
    /**
     * Last session date (leave empty for 3 months)
     */
    endDate?: string | null;
    recurrence?: ('weekly' | 'biweekly' | 'monthly') | null;
    daysOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
    /**
     * Start time in HH:MM format
     */
    startTime?: string | null;
    timezone?: string | null;
  };
  /**
   * Sessions for this class
   */
  sessions?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Instructor biography
   */
  bio?: string | null;
  /**
   * Instructor profile photo
   */
  photo?: (number | null) | Media;
  email: string;
  phone?: string | null;
  /**
   * Teaching specialties (e.g., "Watercolor, Acrylics, Portrait")
   */
  specialties?: string | null;
  /**
   * Whether this instructor is currently available
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * Auto-set based on class/course relationship
   */
  sessionType: 'class' | 'course';
  /**
   * The class this session belongs to
   */
  class?: (number | null) | Class;
  /**
   * The course this session belongs to
   */
  course?: (number | null) | Course;
  /**
   * Session start date and time
   */
  startDateTime: string;
  /**
   * Timezone (e.g., "Europe/Madrid")
   */
  timezone?: string | null;
  status: 'scheduled' | 'cancelled' | 'completed';
  /**
   * Auto-initialized from class/course maxCapacity, updated by bookings
   */
  availableSpots?: number | null;
  /**
   * Internal notes about this specific session
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Course name (e.g., "Watercolor Fundamentals - 4 Week Course")
   */
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Course description and what students will learn
   */
  description?: string | null;
  /**
   * Assigned instructor for this course
   */
  instructor?: (number | null) | Instructor;
  /**
   * Main course image
   */
  featuredImage?: (number | null) | Media;
  /**
   * Additional course images
   */
  gallery?: (number | Media)[] | null;
  /**
   * Total price for entire course in cents (e.g., 18000 = €180.00)
   */
  priceCents: number;
  currency: 'eur' | 'usd';
  /**
   * Maximum participants (applies to ALL course sessions)
   */
  maxCapacity: number;
  /**
   * Duration of each session in minutes
   */
  durationMinutes: number;
  /**
   * Venue or location where course takes place
   */
  location?: string | null;
  /**
   * Category tags for filtering
   */
  tags?: (number | Tag)[] | null;
  /**
   * Published courses are visible on the website
   */
  isPublished?: boolean | null;
  /**
   * Configure automatic session generation. Save course first, then fill this section.
   */
  schedule?: {
    /**
     * First session date
     */
    startDate?: string | null;
    /**
     * Last session date
     */
    endDate?: string | null;
    /**
     * How often sessions repeat
     */
    recurrence?: ('weekly' | 'biweekly' | 'monthly') | null;
    /**
     * Days of the week when sessions occur
     */
    daysOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
    /**
     * Session start time in HH:MM format (e.g., "17:00")
     */
    startTime?: string | null;
    /**
     * Timezone for the schedule
     */
    timezone?: string | null;
  };
  /**
   * Sessions for this course
   */
  sessions?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Type of booking: individual class session or full course
   */
  bookingType: 'class' | 'course';
  /**
   * User who made the booking (optional for guest bookings)
   */
  user?: (number | null) | User;
  /**
   * First name of the person booking
   */
  firstName: string;
  /**
   * Last name of the person booking
   */
  lastName: string;
  /**
   * Email address for booking confirmation
   */
  email: string;
  /**
   * Phone number for contact
   */
  phone: string;
  /**
   * The specific session being booked (for class bookings)
   */
  session?: (number | null) | Session;
  /**
   * The course being enrolled in (for course bookings)
   */
  course?: (number | null) | Course;
  /**
   * Number of spots booked
   */
  numberOfPeople: number;
  status: 'pending' | 'confirmed' | 'cancelled' | 'attended' | 'no-show';
  paymentStatus: 'unpaid' | 'paid' | 'refunded' | 'failed';
  /**
   * Stripe Payment Intent ID
   */
  stripePaymentIntentId?: string | null;
  bookingDate: string;
  /**
   * Expiration time for pending reservations (auto-cleaned up after this time)
   */
  expiresAt?: string | null;
  /**
   * Whether the user has checked in for the class
   */
  checkedIn?: boolean | null;
  /**
   * Internal notes or special requests
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  address?: T;
  city?: T;
  postalCode?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  classType?: T;
  description?: T;
  instructor?: T;
  featuredImage?: T;
  gallery?: T;
  priceCents?: T;
  currency?: T;
  durationMinutes?: T;
  maxCapacity?: T;
  location?: T;
  tags?: T;
  isPublished?: T;
  schedule?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        recurrence?: T;
        daysOfWeek?: T;
        startTime?: T;
        timezone?: T;
      };
  sessions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  instructor?: T;
  featuredImage?: T;
  gallery?: T;
  priceCents?: T;
  currency?: T;
  maxCapacity?: T;
  durationMinutes?: T;
  location?: T;
  tags?: T;
  isPublished?: T;
  schedule?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        recurrence?: T;
        daysOfWeek?: T;
        startTime?: T;
        timezone?: T;
      };
  sessions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  photo?: T;
  email?: T;
  phone?: T;
  specialties?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  sessionType?: T;
  class?: T;
  course?: T;
  startDateTime?: T;
  timezone?: T;
  status?: T;
  availableSpots?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingType?: T;
  user?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  session?: T;
  course?: T;
  numberOfPeople?: T;
  status?: T;
  paymentStatus?: T;
  stripePaymentIntentId?: T;
  bookingDate?: T;
  expiresAt?: T;
  checkedIn?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}